# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawSummary',
            fields=[
                ('law_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('law_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'law_summary',
            },
        ),
    ]
